In [1]:
import torch

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[ 5.1595e+02,  3.0943e-41,  6.0256e-44],
        [ 0.0000e+00,         nan,  0.0000e+00],
        [ 1.3733e-14,  9.5680e+20,  7.2065e+31],
        [ 2.6301e+20,  1.4601e-19,  6.4069e+02],
        [ 4.3066e+21,  1.1824e+22,  4.3066e+21]])


In [4]:
w = torch.empty(3, 5)
torch.nn.init.xavier_normal_(w)

tensor([[ 0.0819,  0.4842, -0.4901, -0.2705,  0.1279],
        [-0.1011,  0.2063, -0.3073, -0.5398,  0.7833],
        [-0.0614, -0.9034, -0.2536,  0.2427,  0.0308]])

In [12]:
w = torch.empty(3, 5)
torch.nn.init.normal_(w, mean=0.5, std=0.2)

tensor([[ 0.2040,  0.8570,  0.3781,  0.2293,  0.9283],
        [ 0.8312,  0.7404,  0.4438,  0.5233,  0.7835],
        [ 0.1669,  0.4792,  0.8216,  0.6270,  0.5834]])

In [22]:
tensor = torch.tensor(1)
tensor.new_full((3, 4), fill_value=3.141592, dtype=torch.float64)

tensor([[ 3.1416,  3.1416,  3.1416,  3.1416],
        [ 3.1416,  3.1416,  3.1416,  3.1416],
        [ 3.1416,  3.1416,  3.1416,  3.1416]], dtype=torch.float64)

In [26]:
tensor = torch.ones((3,4), dtype=torch.float64) * 3.141592
tensor

tensor([[ 3.1416,  3.1416,  3.1416,  3.1416],
        [ 3.1416,  3.1416,  3.1416,  3.1416],
        [ 3.1416,  3.1416,  3.1416,  3.1416]], dtype=torch.float64)

In [3]:
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)
res = torch.bmm(batch1, batch2)
res.size()

torch.Size([10, 3, 5])

In [ ]:
BATCH_SIZE = 2
NUM_MEMORY_BITS = 3
NUM_MEMORY_ADDRESSES = 2

In [62]:
memory = torch.randn(BATCH_SIZE, NUM_MEMORY_BITS, NUM_MEMORY_ADDRESSES)
print(memory)
query_key = torch.randn(BATCH_SIZE, NUM_MEMORY_BITS)
print(query_key)

tensor([[[-0.6074, -0.9557],
         [-0.3845, -0.0649],
         [ 0.9058, -0.9161]],

        [[-0.6229,  0.2015],
         [ 2.0510,  1.9906],
         [ 1.8665,  1.8741]]])
tensor([[ 1.2010, -0.0902,  1.3180],
        [ 0.3142,  0.2392,  1.1101]])


In [63]:
res = torch.matmul(query_key, memory).squeeze(1)
res.size()

torch.Size([2, 2, 2])

In [68]:
memory = torch.tensor(
        [[[0.1, 0.1],
         [ 0.2, 0.4],
         [ 0.3,  0.0]],

        [[ 0.7, 0.1],
         [0.4,  0.1],
         [ 0.1, 0.2]]])
memory

tensor([[[ 0.1000,  0.1000],
         [ 0.2000,  0.4000],
         [ 0.3000,  0.0000]],

        [[ 0.7000,  0.1000],
         [ 0.4000,  0.1000],
         [ 0.1000,  0.2000]]])

In [69]:
query_key = torch.tensor([[0.1, 0.2, 0.3],
        [0.7, 0.4, 0.1]])
query_key

tensor([[ 0.1000,  0.2000,  0.3000],
        [ 0.7000,  0.4000,  0.1000]])

In [70]:
res = torch.matmul(query_key.unsqueeze(1), memory).squeeze(1)
print(res)
print(res.size())

tensor([[ 0.1400,  0.0900],
        [ 0.6600,  0.1300]])
torch.Size([2, 2])
